### PR TITLE
🐛 fixed SES non-dynamic bug

### LINKED ISSUE #40: Non-dynamic mails delivery failure in bulk bug
# Expected Behavior

To fix this bug, if the user tries to send a bulk mail (non dynamic), all the mails get delivered to the respective recipients and logs get displayed.

# Current Behavior

While sending a non dynamic mail in bulk( 50+ recipients ), only the first 50 recipients receive the mail and rest mails are bounced off.
i.e. only the first 50 mails get delivered.

# Failure Information (for bugs)

Only the first 50 mails get delivered.

### PR DESCRIPTION
**Pull request by Developer-R-7**
# Description

Fixed bug , SES allow only maximum of 50 emails(BCC,CC) per mail ,Therefore spitted mailing list into chunks of 49 emails in one array and sending them in batch wise

Fixes #40 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Non Tested bug fix

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Srivastava57Harsh — COMMENTED** [review]
Looks good to me.

File: src/api/campaigns/controller.ts [hunk 1]
```diff
@@ -53,7 +57,14 @@ export const createCampaign = async (body: any, next: NextFunction) => {
         }
       });
     } else {
-      await sendMail(mailList.emails, newCampaign.subject, Body, newCampaign.senderMail);
+      while (mailList.emails.length > 0) {
```
Comment (shawshankkumar) [inline src/api/campaigns/controller.ts:60]: Why await in every iteration? Maybe make an array of promises and them wait for them to resolve together. Improves speed and efficiency. Though you may have to look into the number of emails allowed by ses.

File: src/api/campaigns/controller.ts [hunk 2]
```diff
@@ -53,7 +57,13 @@ export const createCampaign = async (body: any, next: NextFunction) => {
...
       });
     } else {
-      await sendMail(mailList.emails, newCampaign.subject, Body, newCampaign.senderMail);
+      let mailArray = [];
+      while (mailList.emails.length > 0) {
+        mailArray.push(
+          sendMail(mailList.emails.splice(0, emailBatchSize + 1), newCampaign.subject, Body, newCampaign.senderMail),
+        );
+      }
+      await Promise.all(mailArray);
```
Comment (shawshankkumar) [inline src/api/campaigns/controller.ts:66]: Promise.all will work here if all the mails are successfully delivered without any bounces. What if one of the promises is rejected but the rest are resolved? In that case, the API will throw an error despite sending the mails. Instead of promise.all, you can use promise.allSettled which waits for all promises to be settled. 

Refer the mdn docs for more details. 

1. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
2. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

@Developer-R-7 @Srivastava57Harsh You need to come up with a strategy to make sure the mails sent and mails not sent are segregated and the user has a way of seeing them. For example, if the first 49 mails are sent, but the next 49 are not sent, send a message to user saying, we were unable to send mails to some people. Now, you can either list those mails, or give a unique id or a link and then show those mails. For that, you have to store the rejected mails in a db. 

I leave it up to you to come up with a solution.

**Comment by shawshankkumar** [comment]
Merging this.
